## train synface
## trainer
checkpoint_dir: results/synface
save_checkpoint_freq: 500
keep_num_checkpoint: 2
use_logger: true
log_freq: 100
joint_train: false  # true: joint train on multiple images
independent: true  # true: each process has a different input image
reset_weight: true  # true: reset model weights after each epoch
save_results: false
num_stage: 1
flip1_cfg: [false]
flip3_cfg: [true]
stage_len_dict:
    step1: 500
    step2: 500
    step3: 200

## dataloader
image_size: 64
crop: 170
load_gt_depth: true
img_list_path: data/synface/test/list.txt
img_root: data/synface/test/image
latent_root: data/synface/test/latents

## model
model_name: gan2shape_synface
category: synface
share_weight: true  # true: share weight in distributed training
relative_enc: true  # true: use relative latent offset
use_mask: false
add_mean_L: true
add_mean_V: true
num_scale: 1
min_depth: 0.9
max_depth: 1.1
xyz_rotation_range: 60  # (-r,r) in degrees
xy_translation_range: 0.1  # (-t,t) in 3D
z_translation_range: 0  # (-t,t) in 3D
view_scale: 1.2  # enlarge viewpoint variation
collect_iters: 100
batchsize: 16
lr: 0.0001
lam_perc: 0.5
lam_smooth: 0.01
lam_regular: 0.01
pretrain: checkpoints/gan2shape/synface_pretrain.pth
view_mvn_path: checkpoints/view_light/synface_view_mvn.pth
light_mvn_path: checkpoints/view_light/synface_light_mvn.pth
rand_light: [-0.9,0.9,-0.3,0.8,-0.1,0.7,-0.4]

## GAN
channel_multiplier: 1
gan_size: 128
gan_ckpt: checkpoints/stylegan2/stylegan2-synface-config-e.pt
F1_d: 8  # number of mapping network layers used to regularize the latent offset

## renderer
rot_center_depth: 1.0
fov: 10  # in degrees
tex_cube_size: 2
